// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5exDtVKa1IZQ3i18kCOtL-PZ2GbT_HAs',
    appId: '1:359907113729:web:d254c3edc27b084ba6b900',
    messagingSenderId: '359907113729',
    projectId: 'cobros-91ca7',
    authDomain: 'cobros-91ca7.firebaseapp.com',
    storageBucket: 'cobros-91ca7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIcMV_ZBk0SMLrDskhtdHmJVgOy0eohlE',
    appId: '1:359907113729:android:c968c5212577f00ca6b900',
    messagingSenderId: '359907113729',
    projectId: 'cobros-91ca7',
    storageBucket: 'cobros-91ca7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5exDtVKa1IZQ3i18kCOtL-PZ2GbT_HAs',
    appId: '1:359907113729:web:6beed2ad00e23344a6b900',
    messagingSenderId: '359907113729',
    projectId: 'cobros-91ca7',
    authDomain: 'cobros-91ca7.firebaseapp.com',
    storageBucket: 'cobros-91ca7.firebasestorage.app',
  );
}
